site_name: Introducing watsonx.data
# theme:
#   name: material
nav:
  - Introduction: "index.md"
  - Getting Started:
    - Requesting an IBMid: "wxd-reference-ibmid.md"
    - Accessing a workshop: "wxd-reference-workshop.md"
    - Lab Instructions: "wxd-lab-instructions.md"
  - watsonx.data UI: 
    - Watsonx UI Overview: "wxd-watsonui.md"
    - Infrastructure Manager: "wxd-infrastructure.md"
    - Data Manager: "wxd-datamanager.md"
    - Query Workspace: "wxd-queryworkspace.md"
    - Query History: "wxd-queryhistory.md"
    - Access Control: "wxd-accesscontrol.md"
  #- Userids and Passwords: "wxd-reference-passwords.md"

  #- Jupyter Notebook: "wxd-jupyter.md"
  #- Core Components: 
  #  - Presto CLI: "wxd-prestocli.md"
  #  - Presto UI: "wxd-presto.md"
  #  - MinIO UI: "wxd-minio.md"
  #- Presto SQL:
  #  - Analytic Workloads: "wxd-analytics.md"
  #  - Advanced Functions: "wxd-advanced.md"
  #  - Time Travel: "wxd-timetravel.md"
  #  - Federation: "wxd-federation.md"
  #  - System Connector: "wxd-systemconnector.md"
  #- Working with Object Store Buckets: "wxd-objectstore.md"
  #- User Administration and Roles: "wxd-useradmin.md"
  #- Ingesting Data: "wxd-ingest.md"
  #- Documentation: "wxd-reference-documentation.md"
  #- Troubleshooting: "wxd-troubleshooting.md"
  #- Appendix: 
  #  - Disclaimer: "wxd-disclaimer.md"
  #  - Acknowledgements: "wxd-acknowledgements.md"
  #- Glossary: "wxd-glossary.md"

  # Copyright
copyright: Copyright &copy; 2024 IBM 

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: wxd-images/IBM_logo®_rev_RGB.png  
  palette:
    scheme: default
    primary: black
    accent: black

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences    